NAMES	:= describe histogram scatter pair_plot

all: pair_plot
	node pair_plot.js datasets/dataset_train.csv

describe:
	tsc $@.ts

histogram:
	tsc $@.ts

scatter:
	tsc $@.ts

pair_plot:
	tsc $@.ts

svg:
	tsc $@.ts
